version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
    ports:
      - '3306'
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./.docker/data/mysql/dumps:/docker-entrypoint-initdb.d
  php:
    container_name: php
    build:
      context: ./.docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql
    environment:
      PHP_MEMORY_LIMIT: -1
      COMPOSER_MEMORY_LIMIT: -1
      PHP_MAX_EXECUTION_TIME: 6000
      REALPATH_CACHE_SIZE: 4096K
      COMPOSER_PROCESS_TIMEOUT: 6000
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8008:80'
    volumes:
      - .:/var/www/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql